[[https://git.sr.ht/~etalab/sill-consolidate-data/blob/master/LICENSE][https://img.shields.io/badge/Licence-EPL-orange.svg?style=flat-square]]

ℹ️ *This repository is now archived.*

* Consolidate and generate SILL data

=SILL= stands for "socle interministériel de logiciels libres", which
refers to the list of recommended free software for the french public
sector.

You can browse it on [[https://sill.etalab.gouv.fr][sill.etalab.gouv.fr]].

This repository contains the code to generate various =json= files that
are used by the SILL frontend.

It takes SILL data from [[https://git.sr.ht/~etalab/sill/blob/master/sill.csv][this csv file]] and convert it to this [[https://code.gouv.fr/data/sill.json][json]],
also adding Wikidata additional information when available.

The SILL data are published under the [[https://www.etalab.gouv.fr/licence-ouverte-open-licence][Open License 2.0]].

* Contributing

The development of this repository happens on [[https://git.sr.ht/~etalab/sill-consolidate-data][the SourceHut
repository]].  

The code is also published on [[https://github.com/etalab/sill-contents/][GitHub]] to reach more developers, but
please do not send pull requests there.

You can send *patches* by email using [[https://git-send-email.io/][git-send-email.io]].  For your
patches to be processed correctly, configure your local copy with
this:

: git config format.subjectPrefix 'PATCH sill-consolidate-data'

You can also contribute with bug reports, feature requests or general
questions by writing to [[mailto:~etalab/codegouvfr-devel@lists.sr.ht][~etalab/codegouvfr-devel@lists.sr.ht]].

* License

2020-2022 DINUM, Etalab.

This application is published under the [[https://git.sr.ht/~etalab/sill-consolidate-data/blob/master/LICENSE][EPL 2.0 license]].
