[[https://git.sr.ht/~etalab/sill-consolidate-data/blob/master/LICENSE][https://img.shields.io/badge/Licence-EPL-orange.svg?style=flat-square]]

* Consolidate and generate SILL data

=SILL= stands for "Socle Interministériel de Logiciels Libres", which
refers to the list of recommended free software for the french public
sector.

You can browse it on [[https://sill.etalab.gouv.fr][sill.etalab.gouv.fr]].

This repository contains the code to generate various =json= files that
are used by the SILL frontend.

It takes SILL data from [[https://git.sr.ht/~etalab/sill/blob/master/sill.csv][this csv file]] and convert it to =json=, also
adding wikidata additional information when available.

* Contribute

The development of this repository happens on [[https://git.sr.ht/~etalab/sill-consolidate-data][the SourceHut
repository]].  The code is also published on [[https://github.com/etalab/sill-data][GitHub]] to reach more
developers.

Your help is welcome.  You can contribute with bug reports, patches,
feature requests or general questions by sending an email to
[[mailto:~etalab/logiciels-libres@lists.sr.ht][~etalab/logiciels-libres@lists.sr.ht]].

* License

2020-2021 DINUM, Etalab.

This application is published under the [[https://git.sr.ht/~etalab/sill-consolidate-data/blob/master/LICENSE][EPL 2.0 license]].
